# Generated by Django 3.2 on 2022-01-08 06:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_auto_20220107_2031'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_lines', models.CharField(blank=True, max_length=128, null=True, verbose_name='Тэги')),
                ('about_me', models.TextField(blank=True, max_length=512, null=True, verbose_name='Обо мне')),
                ('gender', models.CharField(choices=[('M', 'М'), ('F', 'Ж'), ('A', '-')], default='A', max_length=1, verbose_name='Пол')),
                ('github_profile', models.URLField(blank=True, null=True, verbose_name='Github')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
